language: java
install: mvn install -DskipTests=false
jdk:
  - oraclejdk7
#env: JAVA_OPTS="-server -Djruby.cext.enabled=false -Djruby.compile.invokedynamic=false"
notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
